-- Migration: Renames the 'is_me' column to 'right_me' in the 'messages' table as requested by the user. This is a structural change to the database schema.
-- Executed at: 2025-08-04T00:30:07Z
-- Generated by AI Agent

ALTER TABLE messages RENAME COLUMN is_me TO right_me;
