-- Migration: Inserts a single test message into the 'messages' table. This is done to provide initial data for testing and verifying that the chat UI correctly displays messages from other users. The 'is_me' flag is set to 'false' to simulate a received message.
-- Executed at: 2025-08-03T23:44:09Z
-- Generated by AI Agent

INSERT INTO messages (text, is_me) VALUES ('This is a test message from another user', false);
