-- Migration: Create messages table to store chat history
-- Executed at: 2025-08-03T21:10:11Z
-- Generated by AI Agent

-- Create messages table
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  is_me BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access" ON messages FOR SELECT USING (true);

-- Allow public write access
CREATE POLICY "Allow public write access" ON messages FOR INSERT WITH CHECK (true);
